# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_reg', '0002_auto_20170131_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meme', stdimage.models.StdImageField(blank=True, null=True, upload_to='images/')),
                ('title', models.CharField(max_length=200)),
                ('categories', models.CharField(choices=[('f', 'funny'), ('p', 'politics'), ('r', 'reality')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_memes', to='login_reg.User')),
                ('dislikes', models.ManyToManyField(null=True, related_name='disliked_memes', to='login_reg.User')),
                ('likes', models.ManyToManyField(null=True, related_name='liked_memes', to='login_reg.User')),
            ],
        ),
    ]
