# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 04:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0002_remove_meme_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meme',
            old_name='categories',
            new_name='category',
        ),
    ]
