# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 05:56
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
